name: Build Debian Package

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y debhelper dh-make dh-exec
        
    - name: Prepare Debian package directory
      run: |
        mkdir -p debian/clear-content-deb
        cp -R clear-content-deb/* debian/clear-content-deb/
        cp clear-content-deb/clear-content-deb.deb debian/
        
    - name: Build Debian package
      run: |
        cd debian
        dpkg-deb -b clear-content-deb
        mv clear-content-deb.deb ..
        cd ..
        
    - name: Copy Debian package to repository
      run: |
        cp clear-content-deb.deb $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add clear-content-deb.deb
        git commit -m "Add clear-content-deb.deb"
        git push origin main
