name: Build Debian Package

on:
  push:
    branches:
      - main  # Change this to your main branch name
  workflow_dispatch:  # This enables manual execution


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y debhelper dh-make dh-exec
        
        
    - name: Build Debian package
      run: |
        dpkg-deb -b clear-content-deb
        
    - name: Copy Debian package to repository
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add clear-content-deb.deb
        git commit -m "Add clear-content-deb.deb"
        git push origin main
